OMID-264 Fix deprecated WARNING in check-license stage
apache/phoenix-omid pull request #147
Opened 2023-10-20 19:54 UTC by NihalJain

2023-10-20 19:57 UTC, NihalJain commented
Ensured warning is no longer shown during build.

Tested by first introducing as license error by deleting header from one of existing java file and then running mvn license:check both with/without change, failing as expected.

Next ran mvn license:format to fix header issue.

CC: @stoty

2023-10-25 08:33 UTC, stoty requested changes

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>**/dev-utils/*</exclude>
There is no such file in the repo.
Can we remove this ?

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>dev-support/artifacts/**</exclude>
Can you check all of these ?
Looks like this was copied from HBase or Phoenix.
We should clean up the non-existent directories and files 
(except for the ones generated during build)

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                        <proto>DOUBLESLASH_STYLE</proto>
Just replace the ASL Header in the proto file with the standard Slashstar format one ?
That's what HBase and Phoenix uses.

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>**/pom.xml</exclude>
POM files should have an ASL header,

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>**/src/main/java/org/apache/omid/proto/TSOProto.java</exclude>
No such file, we are generating this dynamically now.

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>**/src/main/java/org/apache/omid/benchmarks/utils/Generator.java</exclude>
These should not be excluded.
Instead, the if the license is indeed ASL compatible (I think it is), then it should be added as a valid license.

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                                <exclude>**/src/main/java/org/apache/omid/committable/hbase/RegionSplitter.java</exclude>
This is already ASL.
I see no need to exclude it, just because it was copied.

2023-10-25 08:33 UTC, stoty commented on pom.xml
> +                            <includes>
Maybe add Yaml files, and add ASL header there ?

2023-10-25 08:36 UTC, stoty approved these changes
I realize that my comments are out of scope for this change.

Can you make a follow-up ticket to really clean up the configuration ?

2023-10-25 08:44 UTC, NihalJain commented
> Can you make a follow-up ticket to really clean up the configuration ?

Sure let me clean up with a follow up JIRA. 

Also do you think we should replace this with spotless? I am well versed with it and based on what I am seeing this plugin is only for headers, which spotless does seemlessly. 

I am okay just cleaning up as well. Let me know what do you think.

2023-10-25 08:48 UTC, stoty commented
I don't know spotless well.
Lets do whatever HBase is doing.

2023-10-25 08:57 UTC, NihalJain commented
> I don't know spotless well.
> Lets do whatever HBase is doing.

HBase uses spotless. Let me create a jira to move to spotless and clean up.

2023-10-31 16:30 UTC, merged